global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: gateway
    static_configs:
      - targets: ['gateway:8080']

  - job_name: git-service
    static_configs:
      - targets: ['git-service:8081']

  - job_name: review-service
    static_configs:
      - targets: ['review-service:8082']

  - job_name: ci-service
    static_configs:
      - targets: ['ci-service:8083']

  - job_name: cd-service
    static_configs:
      - targets: ['cd-service:8084']

  - job_name: analytics-service
    static_configs:
      - targets: ['analytics-service:8085']

  - job_name: runner
    static_configs:
      - targets: ['runner:8086']

  - job_name: hw-automation
    static_configs:
      - targets: ['hw-automation:8087']

  - job_name: sw-automation
    static_configs:
      - targets: ['sw-automation:8088']

  - job_name: device-orch
    static_configs:
      - targets: ['device-orch:8089']

  - job_name: ruby-app
    metrics_path: /metrics
    static_configs:
      - targets: ['ruby-app:3000']
