stages:
  - validate

variables:
  GIT_STRATEGY: clone

api-build:
  stage: validate
  image: golang:1.23
  script:
    - cd gitorcapi
    - go mod tidy
    - go build ./...
  only:
    - merge_requests
    - main

web-build:
  stage: validate
  image: node:20-alpine
  script:
    - cd gitorcweb
    - npm install
    - npm run build
  artifacts:
    paths:
      - gitorcweb/dist/
    expire_in: 1 hour
  only:
    - merge_requests
    - main
