apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orcastack-gateway
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 256m
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  tls:
    - hosts:
        - orcastack.internal.example
      secretName: orcastack-ingress-tls
  rules:
    - host: orcastack.internal.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orcastack-gateway
                port:
                  number: 8080