apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: orcastack-ceph-rbd
  annotations:
    orcastack.io/role: artifacts
provisioner: csi.ceph.com
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  clusterID: orcastack-private-cloud
  pool: orcastack-artifacts
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orcastack-artifacts
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: orcastack-ceph-rbd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orcastack-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: orcastack-ceph-rbd