apiVersion: v1
kind: Namespace
metadata:
  name: orcastack-system
  labels:
    app.kubernetes.io/name: orcastack
    app.kubernetes.io/part-of: orcastack-platform
    orcastack.io/governance: enforced